// The Sky Tablet — original generative cinematic score, desktop + iOS safe.
let ctx=null,master=null,active=[];
function clearNodes(list){for(const n of list){try{n.stop?.()}catch{}try{n.disconnect?.()}catch{}}}
function stop(fade=1){if(!ctx||!master)return;const oldMaster=master,oldNodes=active;master=null;active=[];const t=ctx.currentTime;try{oldMaster.gain.cancelScheduledValues(t);oldMaster.gain.setValueAtTime(Math.max(oldMaster.gain.value,.0001),t);oldMaster.gain.exponentialRampToValueAtTime(.0001,t+fade)}catch{}setTimeout(()=>clearNodes(oldNodes),(fade+.12)*1000)}
function ensureContext(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;if(!ctx)ctx=new AC();return ctx}
function start(){const c=ensureContext();if(!c)return;const build=()=>{if(master)stop(.03);const now=c.currentTime,m=c.createGain(),comp=c.createDynamicsCompressor(),verb=c.createConvolver(),local=[];master=m;active=local;m.gain.setValueAtTime(.0001,now);m.gain.exponentialRampToValueAtTime(1.05,now+.35);m.gain.setValueAtTime(1.05,now+48);m.gain.exponentialRampToValueAtTime(.0001,now+55);m.connect(comp);comp.connect(c.destination);comp.threshold.value=-10;comp.knee.value=12;comp.ratio.value=2.2;comp.attack.value=.01;comp.release.value=.55;const ir=c.createBuffer(2,c.sampleRate*3,c.sampleRate);for(let ch=0;ch<2;ch++){const d=ir.getChannelData(ch);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,2.8)}verb.buffer=ir;const wet=c.createGain();wet.gain.value=.18;verb.connect(wet);wet.connect(comp);local.push(verb,wet,comp,m);
function tone(f,at,dur,g=.1,type='sine',det=0){const o=c.createOscillator(),v=c.createGain();o.type=type;o.frequency.value=f;o.detune.value=det;v.gain.setValueAtTime(.0001,at);v.gain.exponentialRampToValueAtTime(g,at+Math.min(.65,dur*.14));v.gain.setValueAtTime(g,at+dur*.62);v.gain.exponentialRampToValueAtTime(.0001,at+dur);o.connect(v);v.connect(m);v.connect(verb);o.start(at);o.stop(at+dur+.05);local.push(o,v)}
// Speaker-friendly fundamentals and harmonics: audible on iPhone while retaining cinematic depth.
[55,73.42,110,146.83,220,293.66].forEach((f,i)=>{const gs=[.16,.14,.12,.10,.075,.05];tone(f,now+.01,54,gs[i],i<2?'sine':'triangle',-3);tone(f,now+.01,54,gs[i]*.65,i<2?'sine':'triangle',3)});const chords=[[146.83,174.61,220],[130.81,164.81,220],[146.83,185,246.94],[110,146.83,220],[123.47,164.81,246.94],[146.83,196,293.66]];[1,9,17,26,34,42].forEach((st,k)=>chords[k].forEach((f,j)=>tone(f,now+st,9,.075-j*.01,'sawtooth',(j-1)*3)));
function drum(at,a){const o=c.createOscillator(),g=c.createGain();o.frequency.setValueAtTime(165,at);o.frequency.exponentialRampToValueAtTime(55,at+.3);g.gain.setValueAtTime(a,at);g.gain.exponentialRampToValueAtTime(.0001,at+.9);o.connect(g);g.connect(m);g.connect(verb);o.start(at);o.stop(at+.95);local.push(o,g)}[2.5,6,10,14,18,22,25,28,30.5,33,35.3,37.5,39.5,41.5,43.3,45,46.8,48.5,50].forEach((x,i)=>drum(now+x,.28+Math.min(i,12)*.014));function bell(f,at,a){[1,2.01,3.97].forEach((r,i)=>tone(f*r,at,4.8,a/(i+1)))}[[329.63,30],[392,33],[493.88,36],[659.25,39],[783.99,42],[987.77,45]].forEach(([f,t],i)=>bell(f,now+t,.08+i*.006));const b=c.createBuffer(1,c.sampleRate*56,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;const ns=c.createBufferSource(),fil=c.createBiquadFilter(),ng=c.createGain();ns.buffer=b;fil.type='bandpass';fil.frequency.value=700;fil.Q.value=.35;ng.gain.setValueAtTime(.02,now);ng.gain.linearRampToValueAtTime(.06,now+38);ng.gain.linearRampToValueAtTime(.012,now+54);ns.connect(fil);fil.connect(ng);ng.connect(m);ng.connect(verb);ns.start(now);ns.stop(now+55);local.push(ns,fil,ng)};
// resume() is deliberately initiated synchronously inside the user gesture; build after it resolves only when required.
if(c.state==='running')build();else{const p=c.resume();if(p&&typeof p.then==='function')p.then(()=>{if(c.state==='running')build()}).catch(()=>{});else build()}}
window.SkyTabletScore={start,stop};
