// The Sky Tablet — original generative cinematic score. iOS-safe Web Audio unlock.
let ctx=null,master=null,nodes=[],generation=0;
function stop(fade=1.0){generation++;if(!ctx||!master)return;const old=master,t=ctx.currentTime;try{old.gain.cancelScheduledValues(t);old.gain.setValueAtTime(Math.max(old.gain.value,.0001),t);old.gain.exponentialRampToValueAtTime(.0001,t+fade)}catch{}master=null;setTimeout(()=>{for(const n of nodes.splice(0)){try{n.stop?.()}catch{}try{n.disconnect?.()}catch{}}},(fade+.12)*1000)}
async function unlock(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;if(!ctx)ctx=new AC({latencyHint:'interactive'});try{if(ctx.state==='suspended')await ctx.resume();const b=ctx.createBuffer(1,1,22050),s=ctx.createBufferSource(),g=ctx.createGain();g.gain.value=0;s.buffer=b;s.connect(g);g.connect(ctx.destination);s.start(0);if(ctx.state==='suspended')await ctx.resume();return ctx.state==='running'}catch{return false}}
async function start(){const ok=await unlock();if(!ok)return;stop(.03);const my=++generation,now=ctx.currentTime,m=ctx.createGain(),comp=ctx.createDynamicsCompressor(),verb=ctx.createConvolver();master=m;m.gain.setValueAtTime(.0001,now);m.gain.exponentialRampToValueAtTime(.95,now+.65);m.gain.setValueAtTime(.95,now+47);m.gain.exponentialRampToValueAtTime(.0001,now+55);m.connect(comp);comp.connect(ctx.destination);comp.threshold.value=-12;comp.knee.value=14;comp.ratio.value=2.4;comp.attack.value=.012;comp.release.value=.65;const ir=ctx.createBuffer(2,ctx.sampleRate*3.2,ctx.sampleRate);for(let c=0;c<2;c++){const d=ir.getChannelData(c);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,2.7)}verb.buffer=ir;const wet=ctx.createGain();wet.gain.value=.22;verb.connect(wet);wet.connect(comp);
function tone(f,at,dur,g=.1,type='sine',det=0){const o=ctx.createOscillator(),v=ctx.createGain();o.type=type;o.frequency.value=f;o.detune.value=det;v.gain.setValueAtTime(.0001,at);v.gain.exponentialRampToValueAtTime(g,at+Math.min(.8,dur*.15));v.gain.setValueAtTime(g,at+dur*.62);v.gain.exponentialRampToValueAtTime(.0001,at+dur);o.connect(v);v.connect(m);v.connect(verb);o.start(at);o.stop(at+dur+.05);nodes.push(o,v)}
// Add stronger midrange so small iPhone speakers can reproduce the score, while retaining sub-bass on larger speakers.
[36.71,55,73.42,110,146.83,220].forEach((f,i)=>{const gains=[.16,.14,.11,.085,.06,.045];tone(f,now+.02,54,gains[i],i<2?'sine':'triangle',-4);tone(f,now+.02,54,gains[i]*.72,i<2?'sine':'triangle',4)});const chords=[[146.83,174.61,220],[130.81,164.81,220],[146.83,185,246.94],[110,146.83,220],[123.47,164.81,246.94],[146.83,196,293.66]];[1.5,9,17,26,34,42].forEach((st,k)=>chords[k].forEach((f,j)=>tone(f,now+st,9,.07-j*.009,'sawtooth',(j-1)*3)));
function drum(at,a){const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(145,at);o.frequency.exponentialRampToValueAtTime(48,at+.34);g.gain.setValueAtTime(a,at);g.gain.exponentialRampToValueAtTime(.0001,at+.95);o.connect(g);g.connect(m);g.connect(verb);o.start(at);o.stop(at+1);nodes.push(o,g)}[3,7,11,15,19,22,25,28,30.5,33,35.2,37.4,39.4,41.4,43.2,45,46.7,48.4,50].forEach((x,i)=>drum(now+x,.24+Math.min(i,12)*.014));function bell(f,at,a){[1,2.01,3.97].forEach((r,i)=>tone(f*r,at,5,a/(i+1),'sine'))}[[329.63,30],[392,33],[493.88,36],[659.25,39],[783.99,42],[987.77,45]].forEach(([f,t],i)=>bell(f,now+t,.075+i*.006));const b=ctx.createBuffer(1,ctx.sampleRate*56,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;const ns=ctx.createBufferSource(),fil=ctx.createBiquadFilter(),ng=ctx.createGain();ns.buffer=b;fil.type='bandpass';fil.frequency.value=650;fil.Q.value=.35;ng.gain.setValueAtTime(.018,now);ng.gain.linearRampToValueAtTime(.055,now+38);ng.gain.linearRampToValueAtTime(.012,now+54);ns.connect(fil);fil.connect(ng);ng.connect(m);ng.connect(verb);ns.start(now);ns.stop(now+55);nodes.push(ns,fil,ng,verb,wet,comp,m);if(my!==generation)stop(.03)}
window.SkyTabletScore={start,stop,unlock};
